name: 'Damn the Torpedos!'
favicon: null
layout_spectrum: 0.6355201483238488
typography_spectrum: 0.9188161208294332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003470'
    - '#848484'
    - '#eb1c20'
    - '#c2c2c2'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
